"""add_validation_and_conflict_tables

Revision ID: 7f9f0b74dcfc
Revises: 9f60fc74bcc3
Create Date: 2026-09-16 17:49:36.285633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9f0b74dcfc'
down_revision: Union[str, Sequence[str], None] = '9f60fc74bcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_a_id', sa.Integer(), nullable=False),
    sa.Column('doc_b_id', sa.Integer(), nullable=False),
    sa.Column('extraction_a_id', sa.Integer(), nullable=True),
    sa.Column('extraction_b_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_identifier', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('val_a', sa.String(), nullable=True),
    sa.Column('val_b', sa.String(), nullable=True),
    sa.Column('source_ref_a', sa.String(), nullable=True),
    sa.Column('source_ref_b', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_a_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_b_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_a_id'], ['structured_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_b_id'], ['structured_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_conflicts_id'), 'document_conflicts', ['id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('invalid_value', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['structured_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_document_conflicts_id'), table_name='document_conflicts')
    op.drop_table('document_conflicts')
    # ### end Alembic commands ###
